<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class FreezerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('freezers')->insert(array(
            0   => array(
                'id' =>	1	, 
                'code' =>	'	NDF8	', 
                'name' => '	BIORE 03 FREEZER -80 C	', 
                'type' => '	FREEZER	', 
                'specimen_type' => '	COVID-19 PME	', 
                'merk' =>'	PHCBI	', 
                'model' =>'	MDF-DU702VX-PE	',
                'capacity'=>	728	,
                'calibration_time'=>	0	 ,
                'bmn'=>'	025.11.0199.416160.000.KP 2020  3 .08 .01 .41 .024 . 5	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            1   => array(
                'id' =>	2	, 
                'code' =>	'	NDF9	', 
                'name' => '	BIORE 04 FREEZER -80 C	', 
                'type' => '	FREEZER	', 
                'specimen_type' => '	COVID MIGRAN	', 
                'merk' =>'	PHCBI	', 
                'model' =>'	MDF-DU702VX-PE	',
                'capacity'=>	728	,
                'calibration_time'=>	0	 ,
                'bmn'=>'	025.11.0199.416160.000.KP 2020  3 .08 .01 .41 .024 . 4	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            2   => array(
                'id' =>	3	, 
                'code' =>	'	NDF11	', 
                'name' => '	BIORE 06 FREEZER -80 C	', 
                'type' => '	FREEZER	', 
                'specimen_type' => '	NCOV NS/OP	', 
                'merk' =>'	PHCBI	', 
                'model' =>'	MDF-DU702VX-PE	',
                'capacity'=>	728	,
                'calibration_time'=>	0	 ,
                'bmn'=>'	025.11.0199.416160.000.KP 2020  3 .08 .01 .41 .024 . 6	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            3   => array(
                'id' =>	4	, 
                'code' =>	'	NDF13	', 
                'name' => '	PN23.02 FREEZER -80 C	', 
                'type' => '	FREEZER	', 
                'specimen_type' => '	RISKESDAS	', 
                'merk' =>'	THERMOSCIENTIFIC	', 
                'model' =>'	TSX60086V	',
                'capacity'=>	816	,
                'calibration_time'=>	0	 ,
                'bmn'=>'	024.11.0199.416160.000.KP 2018 3 .08 .01 .13. 023 . 95	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>'		'
            ),
            4   => array(
                'id' =>	5	, 
                'code' =>	'	NDF14	', 
                'name' => '	FREEZER -80C. 14	', 
                'type' => '	FREEZER	', 
                'specimen_type' => '	SERUM	', 
                'merk' =>'	PHCBI	', 
                'model' =>'	MDF-U74V-PB	',
                'capacity'=>	728	,
                'calibration_time'=>	1	 ,
                'bmn'=>'	024.11.0199.416160.000.KP 2020 3 .08 .01 .13. 023 . 95	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            5   => array(
                'id' =>	6	, 
                'code' =>	'	NDF15	', 
                'name' => '	FREEZER -80C. 15	', 
                'type' => '	FREEZER	', 
                'specimen_type' => '	SERUM	', 
                'merk' =>'	PHCBI	', 
                'model' =>'	MDF-U74V-PB	',
                'capacity'=>	728	,
                'calibration_time'=>	1	 ,
                'bmn'=>'	024.11.0199.416160.000.KP 2020 3 .08 .01 .13. 023 . 96	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            6   => array(
                'id' =>	7	, 
                'code' =>	'	NDF16	', 
                'name' => '	FREEZER -80C. 16	', 
                'type' => '	FREEZER	', 
                'specimen_type' => '	BLOOD	', 
                'merk' =>'	SANYO	', 
                'model' =>'	MDF-U53V	',
                'capacity'=>	519	,
                'calibration_time'=>	1	 ,
                'bmn'=>'	024.11.0199.416160.000.KP 2008 3 .08 .01 .13. 023 . 30	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            7   => array(
                'id' =>	8	, 
                'code' =>	'	NDF17	', 
                'name' => '	FREEZER -80C. 17	', 
                'type' => '	FREEZER	', 
                'specimen_type' => '	RISET PTM 2016	', 
                'merk' =>'	SANYO	', 
                'model' =>'	MDF-U53V	',
                'capacity'=>	519	,
                'calibration_time'=>	1	 ,
                'bmn'=>'	024.11.0199.416160.000.KP 2008 3 .08 .01 .13. 023 . 26	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            8   => array(
                'id' =>	9	, 
                'code' =>	'	NDF18	', 
                'name' => '	FREEZER -80C. 18	', 
                'type' => '	FREEZER	', 
                'specimen_type' => '	RISET PTM 2016	', 
                'merk' =>'	SANYO	', 
                'model' =>'	MDF-U53V	',
                'capacity'=>	519	,
                'calibration_time'=>	1	 ,
                'bmn'=>'	024.11.0199.416160.000.KP 2008 3 .08 .01 .13. 023 . 29	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            9   => array(
                'id' =>	10	, 
                'code' =>	'	NDF19	', 
                'name' => '	BIORE 07 FREEZER -80 C	', 
                'type' => '	FREEZER	', 
                'specimen_type' => '	NCOV NS/OP	', 
                'merk' =>'	PHCBI	', 
                'model' =>'	MDF-U74V-PE	',
                'capacity'=>	728	,
                'calibration_time'=>	1	 ,
                'bmn'=>'	024.11.0199.416160.000.KP 2020  3 .08 .01 .13 . 90	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            10  => array(
                'id' =>	11	, 
                'code' =>	'	NDF20	', 
                'name' => '	BIORE 08 FREEZER -80 C	', 
                'type' => '	FREEZER	', 
                'specimen_type' => '	NCOV NS/OP	', 
                'merk' =>'	PHCBI	', 
                'model' =>'	MDF-U74V-PE	',
                'capacity'=>	728	,
                'calibration_time'=>	1	 ,
                'bmn'=>'	024.11.0199.416160.000.KP 2020  3 .08 .01 .13 . 92	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            11  => array(
                'id' =>	12	, 
                'code' =>	'	NDF21	', 
                'name' => '	BIORE 09 FREEZER -80 C	', 
                'type' => '	FREEZER	', 
                'specimen_type' => '	COVID MIGRAN	', 
                'merk' =>'	PHCBI	', 
                'model' =>'	MDF-U74V-PE	',
                'capacity'=>	728	,
                'calibration_time'=>	1	 ,
                'bmn'=>'	024.11.0199.416160.000.KP 2020  3 .08 .01 .13 . 91	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            12  => array(
                'id' =>	13	, 
                'code' =>	'	NDF22	', 
                'name' => '	BIORE 10 FREEZER -80 C	', 
                'type' => '	FREEZER	', 
                'specimen_type' => '	NCOV NS/OP	', 
                'merk' =>'	PHCBI	', 
                'model' =>'	MDF-U74V-PB	',
                'capacity'=>	728	,
                'calibration_time'=>	1	 ,
                'bmn'=>'	024.11.0199.416160.000.KP 2020  3 .08 .01 .13 . 93	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            13  => array(
                'id' =>	14	, 
                'code' =>	'	NDF28	', 
                'name' => '	LABDU 05 FREEZER -80 C	', 
                'type' => '	FREEZER	', 
                'specimen_type' => '	PTM 2016	', 
                'merk' =>'	NEW BRUNSWICK	', 
                'model' =>'	U535 -86	',
                'capacity'=>	0	,
                'calibration_time'=>	0	 ,
                'bmn'=>'	no seri 1005-9174-0113	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            14  => array(
                'id' =>	15	, 
                'code' =>	'	NDF29	', 
                'name' => '	LABDU 04 FREEZER -80 C	', 
                'type' => '	FREEZER	', 
                'specimen_type' => '	PTM 2016	', 
                'merk' =>'	SANYO	', 
                'model' =>'	MDF-U72V	',
                'capacity'=>	519	,
                'calibration_time'=>	1	 ,
                'bmn'=>'	024.11.0199.416160.000.KP 2012  3 .08 .01 .13 .023 . 32	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            15  => array(
                'id' =>	16	, 
                'code' =>	'	NDF30	', 
                'name' => '	BIORE 11 FREEZER -80 C	', 
                'type' => '	FREEZER	', 
                'specimen_type' => '	NCOV NS/OP	', 
                'merk' =>'	PHCBI	', 
                'model' =>'	MDF-U74V-PE	',
                'capacity'=>	728	,
                'calibration_time'=>	1	 ,
                'bmn'=>'	024.11.0199.416160.000.KP 2020 3 .08 .01 .13 .023. 94	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            16  => array(
                'id' =>	17	, 
                'code' =>	'	NDF32	', 
                'name' => '	REVCO P FREEZER -80 C	', 
                'type' => '	FREEZER	', 
                'specimen_type' => '	REVCO P (?)	', 
                'merk' =>'	SANYO	', 
                'model' =>'	MDF-U53V	',
                'capacity'=>	519	,
                'calibration_time'=>	1	 ,
                'bmn'=>'	024.11.0199.416160.000.KP 3 .08 .01 .13. 023 . 25	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            17  => array(
                'id' =>	18	, 
                'code' =>	'	NDF1	', 
                'name' => '	FREEZER -80 C. 1	', 
                'type' => '	FREEZER	', 
                'specimen_type' => '	UNKNOWN	', 
                'merk' =>'	SANYO	', 
                'model' =>'	MDF-U72V	',
                'capacity'=>	519	,
                'calibration_time'=>	1	 ,
                'bmn'=>'	024.11.0199.416160.000.KP 2008 3. 08. 01. 13. 023. 19	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>'		'
            ),
            18  => array(
                'id' =>	19	, 
                'code' =>	'	NDF4	', 
                'name' => '	FREEZER -80 C. 4	', 
                'type' => '	FREEZER	', 
                'specimen_type' => '	UNKNOWN	', 
                'merk' =>'	SANYO	', 
                'model' =>'	MDF-U72V	',
                'capacity'=>	519	,
                'calibration_time'=>	1	 ,
                'bmn'=>'	024.11.0199.416160.000.KP 2008 3. 08. 01. 13. 023. 18	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>'		'
            ),
            19  => array(
                'id' =>	20	, 
                'code' =>	'	NDF6	', 
                'name' => '	FREEZER -80C. 6	', 
                'type' => '	FREEZER	', 
                'specimen_type' => '	UNKNOWN	', 
                'merk' =>'	SANYO	', 
                'model' =>'	MDF-U72V	',
                'capacity'=>	519	,
                'calibration_time'=>	1	 ,
                'bmn'=>'	024.11.0199.416160.000.KP 2008 3. 08. 01. 13. 023. 16	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>'		'
            ),
            20  => array(
                'id' =>	21	, 
                'code' =>	'	NDF5	', 
                'name' => '	FREEZER -80C. 5	', 
                'type' => '	FREEZER	', 
                'specimen_type' => '	UNKNOWN	', 
                'merk' =>'	SANYO	', 
                'model' =>'	MDF-U72V	',
                'capacity'=>	519	,
                'calibration_time'=>	1	 ,
                'bmn'=>'	024.11.0199.416160.000.KP 2008 3. 08. 01. 13. 023. 15	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>'		'
            ),
            21  => array(
                'id' =>	22	, 
                'code' =>	'	NK1	', 
                'name' => '	KULKAS 5C. 1	', 
                'type' => '	KULKAS	', 
                'specimen_type' => '	UNKNOWN	', 
                'merk' =>'	THERMOSCIENTIFIC	', 
                'model' =>'	263C-AEV-TSC	',
                'capacity'=>	268	,
                'calibration_time'=>	0	 ,
                'bmn'=>'	024.11.0199.416160.000.KP 2015 3. 08. 01. 55. 007. 19	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            22  => array(
                'id' =>	23	, 
                'code' =>	'	NK2	', 
                'name' => '	KULKAS 5C. 2	', 
                'type' => '	KULKAS	', 
                'specimen_type' => '	UNKNOWN	', 
                'merk' =>'	THERMOSCIENTIFIC	', 
                'model' =>'	263C-AEV-TSC	',
                'capacity'=>	268	,
                'calibration_time'=>	0	 ,
                'bmn'=>'	024.11.0199.416160.000.KP 2015 3. 08. 01. 55. 007. 20	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            23  => array(
                'id' =>	24	, 
                'code' =>	'	NK3	', 
                'name' => '	KULKAS 5C. 3	', 
                'type' => '	KULKAS	', 
                'specimen_type' => '	UNKNOWN	', 
                'merk' =>'	THERMOSCIENTIFIC	', 
                'model' =>'	263C-AEV-TSC	',
                'capacity'=>	268	,
                'calibration_time'=>	0	 ,
                'bmn'=>'	024.11.0199.416160.000.KP 2015 3. 08. 01. 55. 007. 21	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            24  => array(
                'id' =>	25	, 
                'code' =>	'	LEMARI 1	', 
                'name' => '	LEMARI 1 SUHU RUANG	', 
                'type' => '	LEMARI	', 
                'specimen_type' => '	DRY BLOOD	', 
                'merk' =>'	UNKNOWN	', 
                'model' =>'	UNKNOWN	',
                'capacity'=>	0	,
                'calibration_time'=>	0	 ,
                'bmn'=>'	UNKNOWN	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            25  => array(
                'id' =>	26	, 
                'code' =>	'	LEMARI 2	', 
                'name' => '	LEMARI 2 SUHU RUANG	', 
                'type' => '	LEMARI	', 
                'specimen_type' => '	DRY BLOOD	', 
                'merk' =>'	UNKNOWN	', 
                'model' =>'	UNKNOWN	',
                'capacity'=>	0	,
                'calibration_time'=>	0	 ,
                'bmn'=>'	UNKNOWN	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            26  => array(
                'id' =>	27	, 
                'code' =>	'	LEMARI 3	', 
                'name' => '	LEMARI 3 SUHU RUANG	', 
                'type' => '	LEMARI	', 
                'specimen_type' => '	DRY BLOOD	', 
                'merk' =>'	UNKNOWN	', 
                'model' =>'	UNKNOWN	',
                'capacity'=>	0	,
                'calibration_time'=>	0	 ,
                'bmn'=>'	UNKNOWN	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            27  => array(
                'id' =>	28	, 
                'code' =>	'	LEMARI 4	', 
                'name' => '	LEMARI 4 SUHU RUANG	', 
                'type' => '	LEMARI	', 
                'specimen_type' => '	DRY BLOOD	', 
                'merk' =>'	UNKNOWN	', 
                'model' =>'	UNKNOWN	',
                'capacity'=>	0	,
                'calibration_time'=>	0	 ,
                'bmn'=>'	UNKNOWN	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            28  => array(
                'id' =>	29	, 
                'code' =>	'	LEMARI 5	', 
                'name' => '	LEMARI 5 SUHU RUANG	', 
                'type' => '	LEMARI	', 
                'specimen_type' => '	DRY BLOOD	', 
                'merk' =>'	UNKNOWN	', 
                'model' =>'	UNKNOWN	',
                'capacity'=>	0	,
                'calibration_time'=>	0	 ,
                'bmn'=>'	UNKNOWN	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            29  => array(
                'id' =>	30	, 
                'code' =>	'	LEMARI 6	', 
                'name' => '	LEMARI 6 SUHU RUANG	', 
                'type' => '	LEMARI	', 
                'specimen_type' => '	DRY BLOOD	', 
                'merk' =>'	UNKNOWN	', 
                'model' =>'	UNKNOWN	',
                'capacity'=>	0	,
                'calibration_time'=>	0	 ,
                'bmn'=>'	UNKNOWN	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            30  => array(
                'id' =>	31	, 
                'code' =>	'	LEMARI 7	', 
                'name' => '	LEMARI 7 SUHU RUANG	', 
                'type' => '	LEMARI	', 
                'specimen_type' => '	DRY BLOOD	', 
                'merk' =>'	UNKNOWN	', 
                'model' =>'	UNKNOWN	',
                'capacity'=>	0	,
                'calibration_time'=>	0	 ,
                'bmn'=>'	UNKNOWN	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>''
            ),
            31  => array(
                'id' =>	32	, 
                'code' =>	'	NDF10	', 
                'name' => '	BIORE 05 FREEZER -80 C	', 
                'type' => '	FREEZER	', 
                'specimen_type' => '	COVID19 MIGRAN NS/OP	', 
                'merk' =>'	PHCBI	', 
                'model' =>'	MDF-DU702VX-PE	',
                'capacity'=>	729	,
                'calibration_time'=>	1	 ,
                'bmn'=>'	024.11.0199.416160.000.KP 2020 3.08.01.41.024.7	',
                'location'=>'	BIOREPOSITORY	',
                'status'=>'	AKTIF	',
                'picture'=>'		'
            ),

        ));
    }
}
